name: "Feature Request"
description: "I have a specific suggestion!"
body:
  - type: markdown
    attributes:
      value: Thanks for introducing the new feature! Please fill out this form.
  - type: checkboxes
    id: input1
    attributes:
      label: "💻"
      options:
        - label: Would you like to work on this feature?
  - type: dropdown
    attributes:
      label: Package name
      options:
        - commitlint-plugin-card-id
        - commitlint-plugin-scope-ws
        - eslint-config-js
        - eslint-config-jsx
        - eslint-config-ts
        - eslint-config-tsx
        - stylelint
  - type: textarea
    attributes:
      label: What problem are you trying to solve?
      description: |
        A concise description of what the problem is.
      placeholder: |
        I have an issue when [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you'd like
    validations:
      required: true
